// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6gwFsl_4nThDa8h5czOZf6diPqHCgzbk',
    appId: '1:161859047952:web:fce068e020eb54548cb095',
    messagingSenderId: '161859047952',
    projectId: 'flaffy-dev',
    authDomain: 'flaffy-dev.firebaseapp.com',
    storageBucket: 'flaffy-dev.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwDp8tPDAXzEnzuT2aHl8jJ7IQ3LPQJ_U',
    appId: '1:161859047952:android:f943afd5cc6d4dfd8cb095',
    messagingSenderId: '161859047952',
    projectId: 'flaffy-dev',
    storageBucket: 'flaffy-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzn5oK6M_1SBDZvmJihxQCh96zTHuQ_so',
    appId: '1:161859047952:ios:f2da6eb6840b0c1d8cb095',
    messagingSenderId: '161859047952',
    projectId: 'flaffy-dev',
    storageBucket: 'flaffy-dev.appspot.com',
    iosBundleId: 'fluffy.net.fluffy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzn5oK6M_1SBDZvmJihxQCh96zTHuQ_so',
    appId: '1:161859047952:ios:106fde3bc327e0b08cb095',
    messagingSenderId: '161859047952',
    projectId: 'flaffy-dev',
    storageBucket: 'flaffy-dev.appspot.com',
    iosBundleId: 'fluffy.net.fluffy.RunnerTests',
  );
}
